### ISSUE TITLE
Results on outdoor datasets

### ISSUE THREAD

**Issue by zwei-lin** [BLVLab/PiMAE#1]
Hi,
    Thanks for the great work! PiMAE shows excellent results on indoor datasets. 
    I wonder if PiMAE can be applied to outdoor datasets, including nuScenes, Waymo, and KITTI.

**Comment by antonioo-c** [comment]
Hi, thanks for your appreciation.

We have provided **Monocular 3D Object Detection** results on **KITTI** using MonoDETR as well as the finetuning codes, finetuned weights, and evaluation logs in the <code>Model Zoo</code> section. For implementation details please check out the _Appendix_ section in our [paper](https://arxiv.org/abs/2303.08129).

For other outdoor datasets like nuScenes and Waymo, we have not tried out yet. But feel free to use our codes and pretrained weights to try it on your own. We have provided a tutorial <code>Pretrain/tutorial_load.py</code>to use PiMAE's feature extractor. If you encountered any problem, don't hesitate to write issues in here. 

Hope this answers your question. Have a great day.
