### ISSUE TITLE
Some bugs in preparing the SUN RGB-D dataset

### ISSUE THREAD

**Issue by whuhxb** [BLVLab/PiMAE#2]
Hi @zyzkevin @antonioo-c @BLV-LAB 

I have tried to prepare the SUN RGB-D dataset following the votenet https://github.com/facebookresearch/votenet/tree/main/sunrgbd. But, what are the file number in folder calib, depth, image, label, and label_v1? I run the matlab file in windows and the python file in ubuntu, and copied the done matlab files into ubuntu.  As I run python sunrgbd_data.py --gen_v1_data, the following bugs occur like this.

srun -p PV1003q -n 1 -w node15 python sunrgbd_data.py --gen_v1_data
------------- 5051
Traceback (most recent call last):
File "sunrgbd_data.py", line 326, in
save_votes=True, num_point=50000, use_v1=True, skip_empty_scene=False)
File "sunrgbd_data.py", line 202, in extract_sunrgbd_data
objects = dataset.get_label_objects(data_idx)
File "sunrgbd_data.py", line 72, in get_label_objects
return sunrgbd_utils.read_sunrgbd_label(label_filename)
File "/export/home/hanxiaobing/Documents/PlaneNet_PlaneRCNN/DGCNN_PointNet2/SensatUrban/MAE/PiMAE/Pretrain/data/sunrgbd/sunrgbd_utils.py", line 184, in read_sunrgbd_label
lines = [line.rstrip() for line in open(label_filename)]
FileNotFoundError: [Errno 2] No such file or directory: './sunrgbd_trainval/label_v1/005051.txt'

Thanks a lot.

**Comment by antonioo-c** [comment]
Hi,

We didn't encounter this exact issue, so raising this issue at [votenet](https://github.com/facebookresearch/votenet) might be more helpful. Sorry if this doesn't answer your question.
